import = ["~/.config/alacritty/themes/themes/tomorrow_night.toml"]

[window]
padding = { x = 40, y = 20 }
#decorations = "buttonless"
opacity = 1.0
decorations_theme_variant = "Dark"

[font]
normal = { family = "Hack Nerd Font Mono" }
size = 15
offset = { x = 0, y = 10 }
